version: '3'
services:
  ui:
    build:
      context: combined
    command: bash -c "cd static && ../node_modules/.bin/polymer serve --hostname 0.0.0.0 -p 8080"
    volumes:
      - ./combined:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  api:
    build:
      context: combined
    ports:
      - "3000:3000"
    volumes:
      - ./combined:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cordcutting
  proxy:
    build:
      context: proxy
    ports:
      - "80:80"
      - "443:443"
