version: '3'
services:
  ui:
    build:
      context: ui
    container_name: ui
    volumes:
      - ./ui:/usr/src/app
  api:
    image: node:latest
    container_name: api
    volumes:
      - ./api:/usr/src/app
    expose:
      - "3000"
    working_dir: /usr/src/app
    command: "npm start"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cordcutting
  http-proxy:
    image: codekitchen/dinghy-http-proxy
    container_name: dinghy_http_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.dinghy/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
