version: '3'
services:
  ui:
    image: httpd:alpine
    container_name: ui
    volumes:
      - ./ui:/usr/local/apache2/htdocs/
    expose:
      - "80"
  api:
    image: node:latest
    container_name: api
    volumes:
      - ./api:/usr/src/app
    expose:
      - "3000"
    working_dir: /usr/src/app
    entrypoint: "npm start"
  db:
    image: postgres
  http-proxy:
    image: codekitchen/dinghy-http-proxy
    container_name: dinghy_http_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.dinghy/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
