apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cordcut-me
        tier: ui
    spec:
      containers:
      - name: ui
        image: gcr.io/cordcut-me/ui:latest
        livenessProbe:
          httpGet:
            path: /_health
            port: 80
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
